Add abilility to use existing PVC
crowdsecurity/helm-charts pull request #61
Opened 2022-08-24 22:14 UTC by mwinters-stuff

I have had issues with the auto-creating of the persistent volumes, especially after having to re-create the cluster.

I prefer to specify the pvc (eg permanent nfs ).
This PR has a change to allow specifying the existingClaim for each of the 3 volumes.

Eg.

```
lapi:
  persistentVolume:
    # -- Persistent volume for data folder. Stores e.g. registered bouncer api keys
    data:
      enabled: true
      accessModes:
        - ReadWriteOnce
      existingClaim: "nfs-lapi-data-pvc"
      size: 1Gi
    config:
      enabled: true
      accessModes:
        - ReadWriteOnce
      existingClaim: "nfs-lapi-config-pvc"
      size: 100Mi
agent:
  persistentVolume:
    # -- Persistent volume for config folder. Stores local config (parsers, scenarios etc.)
    config:
      enabled: true
      accessModes:
        - ReadWriteOnce
      existingClaim: "nfs-agent-config-pvc"
      size: 100Mi
```

2022-10-12 10:29 UTC, he2ss approved these changes
tested, lgtm :+1: 
I also upgrade crowdsec version by the way.

2022-10-12 11:03 UTC, he2ss requested changes

2022-10-12 11:05 UTC, he2ss commented on charts/crowdsec/templates/agent-persistentVolume.yaml
> +{{ if and (.Values.agent.persistentVolume.config.enabled) (.Values.agent.persistentVolume.config.storageClassName) }}
@mwinters-stuff I need your feedback so we can merge and release a new chart that includes some new features.

2022-10-13 20:34 UTC, mwinters-stuff commented on charts/crowdsec/templates/agent-persistentVolume.yaml
> +{{ if and (.Values.agent.persistentVolume.config.enabled) (.Values.agent.persistentVolume.config.storageClassName) }}
Looks good to me. :)

2022-10-14 08:38 UTC, merged